[package]
name = "aostats"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.9.1"
clap = { version = "4.5.4", features = ["derive"] }
sysinfo = { version = "0.30.8", default-features = false }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
